### ISSUE TITLE
Always crashing?

### ISSUE THREAD

**Issue by cannyboy** [H2CO3/HCDownload#1]
The sample code:

```
HCDownloadViewController *dlvc = [[HCDownloadViewController alloc] init];
dlvc.downloadDirectory = @"/var/mobile/Library/Downloads";
dlvc.delegate = self;
[dlvc downloadURL:[NSURL URLWithString:@"http://news.bbcimg.co.uk/media/images/63987000/jpg/_63987851_63976494.jpg"] userInfo:nil];
```

... always seems to crash on line 264:

```
 [dict setObject:fileHandle forKey:kHCDownloadKeyFileHandle];
```

..with this error:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: fileHandle)'
```

...unless I'm doing something very wrong.

**Comment by H2CO3** [comment]
No, it's not crashing always. If NSFileHandle can't open a file for writing for some reason (i. e. the directory you want to download to does not exist), it returns nil. Unless you provide some more context, I can't really help you with this, but this is most probably not a bug.

**Comment by cannyboy** [comment]
Thanks. I'd assumed HCDownload created the folder. I can see now how wrong I was.
