### ISSUE TITLE
Download stopps after downloading about 120MB of data.

### ISSUE THREAD

**Issue by c05rad** [H2CO3/HCDownload#11]
Hi,
I implemented the DownloadController into my project, and at first when the things i needed to download were tiny it worked without any problem, but as the project grew i found that if i have to download about 270 mb it stopps at about 40% every time. there are multiple files, not a single one. I really don't know what is the issue. 

Thank you , Have a nice day.

**Comment by H2CO3** [comment]
Hi. What does "it stops" mean? Does it freeze? Does the NSURLConnection call the error-reporting delegate methods? Or what does _exactly_ happen?

**Comment by c05rad** [comment]
It just freezes, no other delegate get's called, i tried to download an big file of about 1.8 gb and it worked fine. After that i did an count on the files that get downloaded and it gets to about 350 and than it freezes, nothing happens, no more delegates nothing. no errors. I did an percentage calc and  it just sits at 44 %. Sometimes it stays at 40. With lesser files there is no problem.
I hope i have been clear enough and you somewhat understood my problem. Thank you again for your great work and for this downloader. Have a nice day .

**Comment by H2CO3** [comment]
350 files in parallel? I'm pretty sure the OS imposes an upper bound on the number of open file descriptors. So I don't think I can fix it (neither do I want to do so in this case - it's not a coincidence there's a limit).

As to the files, if again you're downloading a lot of files in parallel, then all the data chunks are being processed at the same time and are present in memory. I suspect that could be simply a memory issue.

**Comment by c05rad** [comment]
Aham, Thank you. I will see what i can do to fix this. Thank you .
