### ISSUE TITLE
Changing HCDownload Background

### ISSUE THREAD

**Issue by iMokhles** [H2CO3/HCDownload#12]
Hi i want to change your project background,

i tried:

```
[self.view setBackgroundColor:[UIColor colorWithPatternImage:[UIImage imageNamed:@"background"]]];
[self.tableView setBackgroundColor:[UIColor colorWithPatternImage:[UIImage imageNamed:@"background"]]];
```

and i have this image of course 

actually i put this code under 

```
if ((self = [super initWithStyle:style]))
```

but didn't worked 

any idea ?

**Comment by iMokhles** [comment]
i did it Thanks

Here is the solution

open HCDownloadViewController

under `if ((self = [super initWithStyle:style])) {`:

```
......
UIImage *image = [UIImage imageNamed:@"imageName.png"];
    UIImageView *backImage = [[[UIImageView alloc] initWithImage:image] autorelease];
    [self.tableView setBackgroundView:backImage];
}
```

Thanks for this project and hope you support Resume Option :+1:

**Comment by H2CO3** [comment]
Hi. I'm glad you have solved this.
