### ISSUE TITLE
Initiate download within HCDownloadViewController

### ISSUE THREAD

**Issue by ghost** [H2CO3/HCDownload#14]
EDIT: no useful information.

**Comment by H2CO3** [comment]
Hi. This project is not maintained anymore, but I could still try to help you – please provide at least a stack trace. It is not clear to me why adding an unrelated object should cause a crash.

**Comment by ghost** [comment]
EDIT: no useful information.

**Comment by H2CO3** [comment]
Thanks. Well, that stack trace is unfortunately not symbolicated. I can't really extract any more useful information from it.

**Comment by ghost** [comment]
Alright, thanks I guess. I’ll find another way.
