### ISSUE TITLE
Using HCDownload within a View Controller

### ISSUE THREAD

**Issue by cannyboy** [H2CO3/HCDownload#2]
I'm trying to set up HCDownload to work within a UIViewController. The UITableView is connected to a UITableView's 'tableView' property, and the HCDownloadViewController is also a property, like this in the header:

```
#import "HCDownloadViewController.h"
@interface DownloadViewController : UIViewController <HCDownloadViewControllerDelegate>
@property (nonatomic, strong) HCDownloadViewController *hcDownloadViewController;
@property (nonatomic, strong) IBOutlet UITableView *tableView;
```

in the ViewController's init method, I create the HCDownloadViewController:

```
self.hcDownloadViewController= [[HCDownloadViewController alloc] init];
```

..and then, when I press a button, I try to start a download like so:

```
- (IBAction)startDownloadButtonTapped:(id)sender
{
   NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
   NSString *documentsDirectory = [paths objectAtIndex:0]; 
   NSString *dataPath = [documentsDirectory stringByAppendingPathComponent:@"Downloads"];
   self.hcDownloadViewController.downloadDirectory = dataPath;
   [self.hcDownloadViewController downloadURL:[NSURL URLWithString:@"http://players.edgesuite.net/videos/big_buck_bunny/bbb_448x252.mp4"] userInfo:[NSDictionary dictionaryWithObjectsAndKeys:@"Bunny", @"kHCDownloadKeyTitle", nil]];
}
```

.. this doesn't seem to do anything. I just get a blank table.. 

If I put the following before the downloadURL line, then I can glimpse the download cell, only if I scroll the cell out of view first (and then the progress view doesn't update until I reload the table cell by scrolling again)

```
[self.tableView setDataSource:self.hcDownloadViewController];
[self.tableView setDelegate:self.self.hcDownloadViewController];
```

Any clues to get this working?

**Comment by H2CO3** [comment]
The download view controller is a table view controller itself, no need for adding additional table view controllers. Yet, you have to somehow _present_ the download view controller, else it's natural you don't see anything...

**Comment by cannyboy** [comment]
I'm not sure what you mean by 'additional' table view controllers. There only seems to be one. But your second sentence gave me the clue I needed:

```
self.hcDownloadViewController.delegate = self;
self.hcDownloadViewController.tableView = self.tableView;
```

.. to the bottom of the button action method.

**Comment by H2CO3** [comment]
Well, setting the table view should not be necessary, but anyways, I'm glad this has been resolved.
