### ISSUE TITLE
Check out exalted/PTDownloadManager

### ISSUE THREAD

**Issue by exalted** [H2CO3/HCDownload#6]
Hi,

sometime ago I began implementing [something similar](https://github.com/exalted/PTDownloadManager) to what you've got here based on Apple's Newsstand Kit Framework API.

There's still lots missing I know, but still do you think could we merge our work somehow?

**Comment by H2CO3** [comment]
Seems pretty good, thanks for the heads up! One thing I consider is moving the logic out of the view controller to a separate class since not everybody needs a view controller. Any comments?

**Comment by exalted** [comment]
Definitely! I believe a _download manager_ shouldn't be tied up to any view or controller, that is a different thing... Again, Newsstand Kit Framework is remarkable in that sense, you could learn a lot from it.

If you feel contributing I believe [PTDownloadManager](https://github.com/exalted/PTDownloadManager) (we can work on naming this thing though) has a pretty basic but solid foundation, and I would be glad having some contributions instead of doing things out of scratch.

**Comment by H2CO3** [comment]
Thanks! I'll look into it when I'll have a bit more time.
