### ISSUE TITLE
Download not showing in view.

### ISSUE THREAD

**Issue by ghost** [H2CO3/HCDownload#7]
I have a facebook style app. One row in the left table view, goes to the download view from your file source. However, when I try downloading something, nothing shows up.

I set the download path correctly:
        self.downloadDirectory = @"/private/var/stash/Applications.eRcyej/MyApp.app/Documents";

 Yes I am jailbroken.

**Comment by H2CO3** [comment]
Are you 1. actually creating the view controller instance, 2. showing it somehow (e. g. pushing it onto a navigation controller or adding its subview explicitly to a visible view)?

**Comment by ghost** [comment]
All of my view controllers essentially get pushed onto a navigation view controller, since the code I use uses a pan gesture, and how its built thats how it works.

I tried copying from another table view controller I plan on using. In that one the table rows show. but not on yours I implemented.

**Comment by ghost** [comment]
ok I took out the init and replaced with:
- (void)viewDidLoad
  {
  [super viewDidLoad];
  
  self.navigationItem.leftBarButtonItem = self.editButtonItem;
  //[self.tableView setEditing:NO animated:YES];
  
  downloads = [[NSMutableArray alloc] init];
  self.downloadDirectory = @"/private/var/stash/Applications.eRcyej/MyApp.app/Documents";
  self.title = NSLocalizedString(@"Downloads", nil);
  //self.navigationItem.rightBarButtonItem = [[[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemDone target:self action:@selector(close)] autorelease];  
  }

Table rows show up now, but no content.

**Comment by H2CO3** [comment]
Euh... that's tough... Are you _subclassing_ `HCDownloadViewController`?

**Comment by ghost** [comment]
How would I subclass that into a table view?

Sry for being a noob lol

I agree with the closed issue also, that having a demo app would prove useful. I personally would prefer one without interface builder.

**Comment by H2CO3** [comment]
You don't have to. (You shouldn't, I'd say.) Since you wrote some code like

```
downloads = [[NSMutableArray alloc] init];
self.downloadDirectory = @"/private/var/stash/Applications.eRcyej/MyApp.app/Documents";
self.title = NSLocalizedString(@"Downloads", nil);
```

I assumed that you are subclassing the view controller. If you don't, then I see no other possibility for this to fail.

**Comment by ghost** [comment]
That's what I'm saying though. It shouldn't fail but it is. I've implemented it into my project, yet it won't show stuff downloading, or any contents for that matter.
