### ISSUE TITLE
How to properly implement into web view.

### ISSUE THREAD

**Issue by ghost** [H2CO3/HCDownload#8]
So I decided to take a different approach in using this. Question is, how would I properly implement it into a web view? As a user decides to download something, how would I enable the download view controller to appear?

I've imported the .h into the webview so far.

Thank you for any info.

**Comment by H2CO3** [comment]
This is not an issue with HCDownload. You should take a look at UIWebViewDelegate's documentation instead.

**Comment by ghost** [comment]
I never said it was an Issue with HCDownload..I was hoping for some help in implementing this.
